//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UlisesWebConfig.Ref_InterfazSacta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ref_InterfazSacta.ServicioInterfazSactaSoap")]
    public interface ServicioInterfazSactaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadoSacta", ReplyAction="*")]
        byte GetEstadoSacta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEstadoSacta", ReplyAction="*")]
        System.Threading.Tasks.Task<byte> GetEstadoSactaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartSacta", ReplyAction="*")]
        void StartSacta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartSacta", ReplyAction="*")]
        System.Threading.Tasks.Task StartSactaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EndSacta", ReplyAction="*")]
        void EndSacta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EndSacta", ReplyAction="*")]
        System.Threading.Tasks.Task EndSactaAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SactaConfGetResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SactaConfGet", ReplyAction="*")]
        UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponse SactaConfGet(UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SactaConfGet", ReplyAction="*")]
        System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponse> SactaConfGetAsync(UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento jcfg del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SactaConfSet", ReplyAction="*")]
        UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponse SactaConfSet(UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SactaConfSet", ReplyAction="*")]
        System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponse> SactaConfSetAsync(UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dataSect del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SectorizeFromSacta", ReplyAction="*")]
        UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponse SectorizeFromSacta(UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SectorizeFromSacta", ReplyAction="*")]
        System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponse> SectorizeFromSactaAsync(UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SactaConfGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SactaConfGet", Namespace="http://tempuri.org/", Order=0)]
        public UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequestBody Body;
        
        public SactaConfGetRequest() {
        }
        
        public SactaConfGetRequest(UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SactaConfGetRequestBody {
        
        public SactaConfGetRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SactaConfGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SactaConfGetResponse", Namespace="http://tempuri.org/", Order=0)]
        public UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponseBody Body;
        
        public SactaConfGetResponse() {
        }
        
        public SactaConfGetResponse(UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SactaConfGetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SactaConfGetResult;
        
        public SactaConfGetResponseBody() {
        }
        
        public SactaConfGetResponseBody(string SactaConfGetResult) {
            this.SactaConfGetResult = SactaConfGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SactaConfSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SactaConfSet", Namespace="http://tempuri.org/", Order=0)]
        public UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequestBody Body;
        
        public SactaConfSetRequest() {
        }
        
        public SactaConfSetRequest(UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SactaConfSetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jcfg;
        
        public SactaConfSetRequestBody() {
        }
        
        public SactaConfSetRequestBody(string jcfg) {
            this.jcfg = jcfg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SactaConfSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SactaConfSetResponse", Namespace="http://tempuri.org/", Order=0)]
        public UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponseBody Body;
        
        public SactaConfSetResponse() {
        }
        
        public SactaConfSetResponse(UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SactaConfSetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SactaConfSetResult;
        
        public SactaConfSetResponseBody() {
        }
        
        public SactaConfSetResponseBody(bool SactaConfSetResult) {
            this.SactaConfSetResult = SactaConfSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SectorizeFromSactaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SectorizeFromSacta", Namespace="http://tempuri.org/", Order=0)]
        public UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequestBody Body;
        
        public SectorizeFromSactaRequest() {
        }
        
        public SectorizeFromSactaRequest(UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SectorizeFromSactaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint Version;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataSect;
        
        public SectorizeFromSactaRequestBody() {
        }
        
        public SectorizeFromSactaRequestBody(uint Version, string dataSect) {
            this.Version = Version;
            this.dataSect = dataSect;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SectorizeFromSactaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SectorizeFromSactaResponse", Namespace="http://tempuri.org/", Order=0)]
        public UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponseBody Body;
        
        public SectorizeFromSactaResponse() {
        }
        
        public SectorizeFromSactaResponse(UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SectorizeFromSactaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SectorizeFromSactaResult;
        
        public SectorizeFromSactaResponseBody() {
        }
        
        public SectorizeFromSactaResponseBody(string SectorizeFromSactaResult) {
            this.SectorizeFromSactaResult = SectorizeFromSactaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioInterfazSactaSoapChannel : UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioInterfazSactaSoapClient : System.ServiceModel.ClientBase<UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap>, UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap {
        
        public ServicioInterfazSactaSoapClient() {
        }
        
        public ServicioInterfazSactaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioInterfazSactaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInterfazSactaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInterfazSactaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte GetEstadoSacta() {
            return base.Channel.GetEstadoSacta();
        }
        
        public System.Threading.Tasks.Task<byte> GetEstadoSactaAsync() {
            return base.Channel.GetEstadoSactaAsync();
        }
        
        public void StartSacta() {
            base.Channel.StartSacta();
        }
        
        public System.Threading.Tasks.Task StartSactaAsync() {
            return base.Channel.StartSactaAsync();
        }
        
        public void EndSacta() {
            base.Channel.EndSacta();
        }
        
        public System.Threading.Tasks.Task EndSactaAsync() {
            return base.Channel.EndSactaAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponse UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap.SactaConfGet(UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest request) {
            return base.Channel.SactaConfGet(request);
        }
        
        public string SactaConfGet() {
            UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest inValue = new UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest();
            inValue.Body = new UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequestBody();
            UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponse retVal = ((UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap)(this)).SactaConfGet(inValue);
            return retVal.Body.SactaConfGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponse> UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap.SactaConfGetAsync(UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest request) {
            return base.Channel.SactaConfGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SactaConfGetResponse> SactaConfGetAsync() {
            UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest inValue = new UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequest();
            inValue.Body = new UlisesWebConfig.Ref_InterfazSacta.SactaConfGetRequestBody();
            return ((UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap)(this)).SactaConfGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponse UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap.SactaConfSet(UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest request) {
            return base.Channel.SactaConfSet(request);
        }
        
        public bool SactaConfSet(string jcfg) {
            UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest inValue = new UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest();
            inValue.Body = new UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequestBody();
            inValue.Body.jcfg = jcfg;
            UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponse retVal = ((UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap)(this)).SactaConfSet(inValue);
            return retVal.Body.SactaConfSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponse> UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap.SactaConfSetAsync(UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest request) {
            return base.Channel.SactaConfSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SactaConfSetResponse> SactaConfSetAsync(string jcfg) {
            UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest inValue = new UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequest();
            inValue.Body = new UlisesWebConfig.Ref_InterfazSacta.SactaConfSetRequestBody();
            inValue.Body.jcfg = jcfg;
            return ((UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap)(this)).SactaConfSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponse UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap.SectorizeFromSacta(UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest request) {
            return base.Channel.SectorizeFromSacta(request);
        }
        
        public string SectorizeFromSacta(uint Version, string dataSect) {
            UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest inValue = new UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest();
            inValue.Body = new UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequestBody();
            inValue.Body.Version = Version;
            inValue.Body.dataSect = dataSect;
            UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponse retVal = ((UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap)(this)).SectorizeFromSacta(inValue);
            return retVal.Body.SectorizeFromSactaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponse> UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap.SectorizeFromSactaAsync(UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest request) {
            return base.Channel.SectorizeFromSactaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaResponse> SectorizeFromSactaAsync(uint Version, string dataSect) {
            UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest inValue = new UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequest();
            inValue.Body = new UlisesWebConfig.Ref_InterfazSacta.SectorizeFromSactaRequestBody();
            inValue.Body.Version = Version;
            inValue.Body.dataSect = dataSect;
            return ((UlisesWebConfig.Ref_InterfazSacta.ServicioInterfazSactaSoap)(this)).SectorizeFromSactaAsync(inValue);
        }
    }
}
